language: node_js
node_js:
  - "node"
addons:
  code_climate:
    repo_token: 4408bc25e633c3894834c4ad69038d29d6036755b8fd78f191092f010ab27e22
install:
  - npm ci
script: npm test
after_success:
  - npx codeclimate-test-reporter < ./coverage/lcov.info
